name: BennieMosher.dev CI for Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci-terraform:
    name: Continuous Integration for Terraform
    uses: "benniemosher-dev/.github/.github/workflows/ci-terraform.yml@bam/add-terraform-workflow"
    secrets:
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

